// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test_API.Models;

#nullable disable

namespace Test_API.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20230426041553_Add_DataBase")]
    partial class Add_DataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test_API.Models.Orders.DbDTO.OrderDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Test_API.Models.Orders.DbDTO.ProductDTO", b =>
                {
                    b.Property<int>("ProductDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductDTOId"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderDTOId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("ProductDTOId");

                    b.HasIndex("OrderDTOId");

                    b.ToTable("ProductDTO");
                });

            modelBuilder.Entity("Test_API.Models.Orders.DbDTO.ProductDTO", b =>
                {
                    b.HasOne("Test_API.Models.Orders.DbDTO.OrderDTO", "OrderDTO")
                        .WithMany("Products")
                        .HasForeignKey("OrderDTOId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("OrderDTO");
                });

            modelBuilder.Entity("Test_API.Models.Orders.DbDTO.OrderDTO", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
